### PR TITLE
fixing issue discovered testing install on mac

### PR DESCRIPTION
**Pull request by bfitzpat**
Signed-off-by: bfitzpat@redhat.com <bfitzpat@redhat.com>

### CODE REVIEW

**Comment by bfitzpat** [comment]
Thanks for finding this @djelinek !

**Comment by bfitzpat** [comment]
This is for https://issues.jboss.org/browse/FUSETOOLS2-59

**Comment by djelinek** [comment]
I think we also need to add `|| shell.isMacOS()` here https://github.com/camel-tooling/vscode-camelk/blob/cb55607792539cf2cb759ddbf60a8bea7b7bf1cb/src/installer.ts#L266-L268

WDYT @bfitzpat ?

**Comment by bfitzpat** [comment]
> And another question, is here any logic for waiting until all is downloaded? because VSCode shows this notifications even if _kubectl_ file exists

Those messages are coming from the Microsoft Kubernetes extension, not from Camel K - so I don't control them. We require the Kubernetes extension to be there so we can use the kubectl api, but we don't have much control over that side of it.

**Comment by djelinek** [comment]
> Those messages are coming from the Microsoft Kubernetes extension, not from Camel K - so I don't control them. We require the Kubernetes extension to be there so we can use the kubectl api, but we don't have much control over that side of it.

OK, I see, thanks for clarification.

**Pull request merged**
