### PR TITLE
updated package lock triggered by npm install on clean master

### PR DESCRIPTION
**Pull request by lhein**
Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>

### CODE REVIEW

**Comment by apupier** [comment]
Why are there so many changes? isn't dependabot supposed to upgrade dependencies? Are there ways to avoid big bang like that?

**Comment by lhein** [comment]
Ask npm :)

**Comment by apupier** [comment]
if I run locally, I end up with the same files than on current master. See https://github.com/lhein/vscode-camelk/pull/1

**Comment by lhein** [comment]
Closing this PR as we get no agreement for a merge.

**Comment by apupier** [comment]
reasons provided for not merging:
- Avoid the file to have thousands of modified lines on each PR. For instance, it is easier to avoid having a package-lock.json that might point to an alternative npm registry manager that can contain malicious code.
- No need to commit of package-lock.json until we understand what is going on sounds like a good thing as no Pull request or planned work (as far as I know) is blocked by that.
It will be a problem only when you add a dependency or update one manually without relying on dependabot.

As nothing is blocked, there is time to investigate on this various track if needed:
- google search leads to find old bugs leading to differences when stuff is called with [empty node_modules ](https://npm.community/t/npm-install-changes-package-lock-extensively/7653/3)for instance
- What are the changes more precisely?
- raise a question on npm support
- can it be reproduced on other OS than ArchLinux?
- Are there global npm configurations that can have an impact on that?

**Pull request closed without merging**
