### PR TITLE
FUSETOOLS2-1769 Remove requests rename vscode-test

### PR DESCRIPTION
**Pull request by unsortedhashsets**
Hi,

- npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142 -> remove
~~- npm WARN deprecated vscode-test@1.6.1: This package has been renamed to @vscode/test-electron, please update to the new name -> rename~~ [1245](https://github.com/camel-tooling/vscode-camelk/pull/1245)

Issues:
- [FUSETOOLS2-1769](https://issues.redhat.com/browse/FUSETOOLS2-1769)
- [FUSETOOLS2-1711](https://issues.redhat.com/browse/FUSETOOLS2-1711)

\+ by accident:
- [FUSETOOLS2-1730](https://issues.redhat.com/browse/FUSETOOLS2-1730)
- [FUSETOOLS2-1710](https://issues.redhat.com/browse/FUSETOOLS2-1710)
- [FUSETOOLS2-1712](https://issues.redhat.com/browse/FUSETOOLS2-1712)

### CODE REVIEW

**Review by joshiraez — APPROVED** [review]

**Comment by joshiraez** [comment]
Does this fix https://issues.redhat.com/browse/FUSETOOLS2-1730 as well?

**Comment by unsortedhashsets** [comment]
> Does this fix https://issues.redhat.com/browse/FUSETOOLS2-1730 as well?

@joshiraez thanks! Seems, yes.  request@2.88.2 was mentioned also in [FUSETOOLS2-1711](https://issues.redhat.com/browse/FUSETOOLS2-1711) so I thought that it is a part of it... some misunderstanding.

Only I need to rebase

**Comment by unsortedhashsets** [comment]
Hi, @joshiraez!
Sorry to bother you.

I have checked issues related to [FUSETOOLS2-1730](https://issues.redhat.com/browse/FUSETOOLS2-1730): 

- [FUSETOOLS2-1710](https://issues.redhat.com/browse/FUSETOOLS2-1710)
- [FUSETOOLS2-1712](https://issues.redhat.com/browse/FUSETOOLS2-1712)

Seems to be fixed with that PR, 
I have added comments according to each issue to [FUSETOOLS2-1769](https://issues.redhat.com/browse/FUSETOOLS2-1769)

**Comment by joshiraez** [comment]
Yes, I just saw your comments in the email. Thank you very much for tracking them :). I'll double check but I think you did the whole upgrade in one sweep.

**Comment by joshiraez** [comment]
@unsortedhashsets Heads up, take care with the rebase as @vscode/test-electron has been upgraded also in https://github.com/camel-tooling/vscode-camelk/pull/1245 to a higher version (2.1.X I believe). Everything else is untouched.

**Comment by unsortedhashsets** [comment]
@joshiraez Thanks for the ping, I didn't receive label change notifications

**Review by joshiraez — APPROVED** [review]

**Review by apupier — APPROVED** [review]

**Pull request merged**
