### PR TITLE
Update VS Code extension tester to 4.0.2

### PR DESCRIPTION
**Pull request by apupier**
required to fix master after vs code regression for url availability affecting vscode-extension-tester https://github.com/redhat-developer/vscode-extension-tester/issues/257

### CODE REVIEW

**Comment by apupier** [comment]
```
  1) Tooling for Apache Camel K extension
       Extensions view
         "before all" hook for "Find extension":
     TypeError: extensionView.openView is not a function
      at Function.<anonymous> (node_modules/vscode-uitests-tooling/out/workbench/Marketplace.js:98:57)
```

**Comment by apupier** [comment]
cc @djelinek @jrichter will search later myself but if you know what needs ot be updated out of your head it will save me time

**Comment by djelinek** [comment]
I suppose problem will be fixed with next release of `vscode-uitests-tooling`

**Comment by apupier** [comment]
covered by https://github.com/camel-tooling/vscode-camelk/pull/714

**Pull request closed without merging**
