### PR TITLE
FUSETOOLS2-1066 - switching to latest Camel K version 1.4.0

### PR DESCRIPTION
**Pull request by lhein**
Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>

### CODE REVIEW

**Review by apupier — CHANGES_REQUESTED** [review]
- the version of Camel dependencies needs to be updated from 3.7.0 to 3.9.0 
https://github.com/camel-tooling/vscode-camelk/blob/9f8ad157c9c76de099dd345b0265f389a5bad043/src/JavaDependenciesManager.ts#L22
https://github.com/apache/camel-k-runtime/blob/7a0629cfcad4a295196e9392e478d3153290258a/pom.xml#L41
- better to update minikube in another commit as it is unrealted to Camel K 1.4.0 (unless it requires this updated new version?)

**Comment by lhein** [comment]
Thanks Aurelien. I missed that Camel version bump.

**Review by apupier — CHANGES_REQUESTED** [review]
- please add an entry in teh changelog
- I think we should wait for camel language server to support the new way of wrting mvn dependency in modeline to merge this one

**Comment by lhein** [comment]
yes. good points.

**Review by apupier — APPROVED** [review]

**Pull request merged**
