### PR TITLE
Fix compilation error as node introduced a different signature

### PR DESCRIPTION
**Pull request by apupier**
Signed-off-by: Aurélien Pupier <apupier@redhat.com>

### CODE REVIEW

**Comment by bfitzpat** [comment]
Tried this locally and (as you see with the build), the tests just hang... forever.

I modified it slightly to...

```
			sr.on('close', function (exitCode, signal) {
				if (exitCode) {
					if(exitCode === 0){
						if(wholeOutData !== ''){
							resolve(wholeOutData);
						} else {
							resolve("0");
						}
					} else if (exitCode === null) {
						if (signal === null) {
							reject("Closed with no exit code and no signal.");
						} else {
							reject(signal.toString());
						}
					} else {
						reject(exitCode.toString());
					}
				}
			});
```

And I'm seeing the same behavior here.

**Comment by bfitzpat** [comment]
> Can you precise which test?
> The master is currently broken due to regression in Camel K 1.3.0 [apache/camel-k#1872](https://github.com/apache/camel-k/issues/1872)

It just hangs here. Maybe it's due to the same regression?

**Comment by apupier** [comment]
> > Can you precise which test?
> > The master is currently broken due to regression in Camel K 1.3.0 [apache/camel-k#1872](https://github.com/apache/camel-k/issues/1872)
> 
> It just hangs here. Maybe it's due to the same regression?

The CI job is finishing without infinite hang. Sounds a problem in your local environment.

**Comment by bfitzpat** [comment]
Apparently it's just the super long timeouts that caused me to think it had frozen. I do see more failures locally than up on circle.ci, but I believe that's because I don't have a proper runtime configured.

```
  73 passing (6m)
base.js:362
  2 pending
base.js:368
  12 failing
base.js:375
  1) Should do completion in Camel K standalone files
       Completes from method for Java:
     AssertionError [ERR_ASSERTION]: Camel Java dependencies not downloaded in reasonable time (240000). The one that were downloaded are: 
  	at /home/bfitzpat/github/vscode-camelk/out/src/test/suite/_completion/completion.java.test.js:61:22

base.js:294
  2) Camel K Task Completion
       Completion for traits:

      AssertionError: expected [ Array(30) ] to have a length of 29 but got 30
      + expected - actual

      -30
      +29
      
  	at Suite.<anonymous> (github/vscode-camelk/out/src/test/suite/CamelKTaskCompletionItemProvider.test.js:62:36)
  	at Generator.next (<anonymous>)
  	at fulfilled (github/vscode-camelk/out/src/test/suite/CamelKTaskCompletionItemProvider.test.js:21:58)
  	at processTicksAndRejections (internal/process/task_queues.js:94:5)

 3) Test command to create an Apache Camel K integration file
       Can create a new Groovy integration file:
     Error: Timed out after waiting for 5000ms
  	at Timeout.onTimeout (github/vscode-camelk/node_modules/async-wait-until/src/waitUntil.js:53:14)
  	at listOnTimeout (internal/timers.js:531:17)
  	at processTimers (internal/timers.js:475:7)

base.js:294
  4) ensure kamel and kubectl are available
       ensure can activate kamel cli:
     Error: Timeout of 20000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/bfitzpat/github/vscode-camelk/out/src/test/suite/kamel.test.js)
  	at listOnTimeout (internal/timers.js:531:17)
  	at processTimers (internal/timers.js:475:7)

base.js:294
  5) Check can deploy default examples
       Check can deploy from a task:
     AssertionError: No integration has shown up in Camel K Integration provider view. (Nota: it requires that Camel K instance is reachable.)
Error: Timed out after waiting for 10000ms
  	at /home/bfitzpat/github/vscode-camelk/out/src/test/suite/StartIntegration.test.js:159:27
  	at Generator.throw (<anonymous>)
  	at rejected (github/vscode-camelk/out/src/test/suite/StartIntegration.test.js:22:65)
  	at runNextTicks (internal/process/task_queues.js:59:5)
  	at processTimers (internal/timers.js:472:9)

base.js:294
  6) Check can deploy default examples
       Check can deploy on specific namespace:

      AssertionError: expected 'The connection to the server localhost:8080 was refused - did you specify the right host or port?\n' to equal ''
      + expected - actual

      -The connection to the server localhost:8080 was refused - did you specify the right host or port?
      
  	at /home/bfitzpat/github/vscode-camelk/out/src/test/suite/StartIntegration.test.js:130:23
  	at Generator.next (<anonymous>)
  	at fulfilled (github/vscode-camelk/out/src/test/suite/StartIntegration.test.js:21:58)

  7) Check can deploy default examples
       Check basic deployments for each languages
         Check can deploy Java example:
     AssertionError: No integration has shown up in Camel K Integration provider view. (Nota: it requires that Camel K instance is reachable.)
Error: Timed out after waiting for 10000ms
  	at /home/bfitzpat/github/vscode-camelk/out/src/test/suite/StartIntegration.test.js:159:27
  	at Generator.throw (<anonymous>)
  	at rejected (github/vscode-camelk/out/src/test/suite/StartIntegration.test.js:22:65)

base.js:294
  8) Check can deploy default examples
       Check basic deployments for each languages
         Check can deploy XML example:
     AssertionError: No integration has shown up in Camel K Integration provider view. (Nota: it requires that Camel K instance is reachable.)
Error: Timed out after waiting for 10000ms
  	at /home/bfitzpat/github/vscode-camelk/out/src/test/suite/StartIntegration.test.js:159:27
  	at Generator.throw (<anonymous>)
  	at rejected (github/vscode-camelk/out/src/test/suite/StartIntegration.test.js:22:65)

base.js:294
  9) Check can deploy default examples
       Check basic deployments for each languages
         Check can deploy Yaml example:
     AssertionError: No integration has shown up in Camel K Integration provider view. (Nota: it requires that Camel K instance is reachable.)
Error: Timed out after waiting for 10000ms
  	at /home/bfitzpat/github/vscode-camelk/out/src/test/suite/StartIntegration.test.js:159:27
  	at Generator.throw (<anonymous>)
  	at rejected (github/vscode-camelk/out/src/test/suite/StartIntegration.test.js:22:65)

base.js:294
  10) Check can deploy default examples
       Check basic deployments for each languages
         Check can deploy Groovy example:
     AssertionError: No integration has shown up in Camel K Integration provider view. (Nota: it requires that Camel K instance is reachable.)
Error: Timed out after waiting for 10000ms
  	at /home/bfitzpat/github/vscode-camelk/out/src/test/suite/StartIntegration.test.js:159:27
  	at Generator.throw (<anonymous>)
  	at rejected (github/vscode-camelk/out/src/test/suite/StartIntegration.test.js:22:65)

base.js:294
  11) Check can deploy default examples
       Check basic deployments for each languages
         Check can deploy JavaScript example:
     AssertionError: No integration has shown up in Camel K Integration provider view. (Nota: it requires that Camel K instance is reachable.)
Error: Timed out after waiting for 10000ms
  	at /home/bfitzpat/github/vscode-camelk/out/src/test/suite/StartIntegration.test.js:159:27
  	at Generator.throw (<anonymous>)
  	at rejected (github/vscode-camelk/out/src/test/suite/StartIntegration.test.js:22:65)

base.js:294
  12) Check can deploy default examples
       Check basic deployments for each languages
         Check can deploy Kotlin example:
     AssertionError: No integration has shown up in Camel K Integration provider view. (Nota: it requires that Camel K instance is reachable.)
Error: Timed out after waiting for 10000ms
  	at /home/bfitzpat/github/vscode-camelk/out/src/test/suite/StartIntegration.test.js:159:27
  	at Generator.throw (<anonymous>)
  	at rejected (github/vscode-camelk/out/src/test/suite/StartIntegration.test.js:22:65)

base.js:294
reports written to /home/bfitzpat/github/vscode-camelk/coverage
coverage.js:136
Uncaught Error: write EPIPE
```

**Comment by apupier** [comment]
> I do see more failures locally than up on circle.ci, but I believe that's because I don't have a proper runtime configured.

yes

**Pull request closed without merging**
