### PR TITLE
FUSETOOLS2-10 Adding Namespace Support

### PR DESCRIPTION
**Pull request by bfitzpat**
Signed-off-by: Brian Fitzpatrick <bfitzpat@redhat.com>

### CODE REVIEW

**Comment by apupier** [comment]
if I understand well it means that we don't rely anymore on the system namespace? The one used from command-line and rom kubernetes extension.

**Comment by bfitzpat** [comment]
> if I understand well it means that we don't rely anymore on the system namespace? The one used from command-line and rom kubernetes extension.

It always just used the "default", but now we're being more explicit about it by providing it via the --namespace argument at the CLI

**Comment by apupier** [comment]
> > if I understand well it means that we don't rely anymore on the system namespace? The one used from command-line and rom kubernetes extension.
> 
> It always just used the "default", but now we're being more explicit about it by providing it via the --namespace argument at the CLI

I don't think that it is using always "default", it is using the "current namespace" https://github.com/apache/camel-k/blame/master/README.adoc#L44
Which means that now we have the kamel command that can be unsynchronized from the Kubernetes view and from the Kamel CLI

**Comment by bfitzpat** [comment]
> I don't think that it is using always "default", it is using the "current namespace" https://github.com/apache/camel-k/blame/master/README.adoc#L44
> Which means that now we have the kamel command that can be unsynchronized from the Kubernetes view and from the Kamel CLI

Well, we can make it optional then -- if it's empty it is ignored and goes with the default that is specified by the system. If it's populated, it is used and overrides it. Sound good @apupier ?

**Comment by apupier** [comment]
sounds good

maybe instead of "empty" have a label like "use current namespace"?

**Comment by bfitzpat** [comment]
Created https://github.com/camel-tooling/vscode-camelk/pull/186

**Pull request merged**
