### PR TITLE
FUSETOOLS2-712 - upgrade minikube to 1.13.1 on Travis infra

### PR DESCRIPTION
**Pull request by apupier**
Signed-off-by: Aurélien Pupier <apupier@redhat.com>

### CODE REVIEW

**Review by bfitzpat — CHANGES_REQUESTED** [review]
Why are we upgrading? Is it merely a version bump or is there a more specific reason? There is no justification for the bump in the JIRA or the PR, so it's without context

**Comment by apupier** [comment]
> Why are we upgrading? Is it merely a version bump or is there a more specific reason? There is no justification for the bump in the JIRA or the PR, so it's without context

it is to fill technical debt.
it also ensures to be working with latest available version.
Dependabot is not able to update automatically as this is not a regular dependency.

**Comment by bfitzpat** [comment]
> it is to fill technical debt.
> it also ensures to be working with latest available version.
> Dependabot is not able to update automatically as this is not a regular dependency.

This would be good to include in the JIRA so when our QE folks look at it they have some context to base it on. :)

**Comment by apupier** [comment]
> > it is to fill technical debt.
> > it also ensures to be working with latest available version.
> > Dependabot is not able to update automatically as this is not a regular dependency.
> 
> This would be good to include in the JIRA so when our QE folks look at it they have some context to base it on. :)

done

**Review by bfitzpat — APPROVED** [review]

**Review by lhein — APPROVED** [review]

**Pull request merged**
