### PR TITLE
FUSETOOLS2-604 - Upgrade Java on Jenkins to Java 11

### PR DESCRIPTION
**Pull request by apupier**
as it is required now for VS Code java and so Ui tests

Signed-off-by: Aurélien Pupier <apupier@redhat.com>

### CODE REVIEW

**Review by lhein — APPROVED** [review]

**Comment by apupier** [comment]
set back to ready to review as condition not meet to merge: all developers of the project approved or one approval and 24 hours since marked as ready for review

**Comment by lhein** [comment]
is that some new rule that prevents us to mark a PR as review done and ready to merge if not all devs reviewed and 24hours are have not passed? I think that is pretty silly. A single approval is enough and tbh I think its up to the PR creator to keep the PR open for 24hrs ;)

**Comment by apupier** [comment]
> is that some new rule that prevents us to mark a PR as review done and ready to merge if not all devs reviewed and 24hours have not passed?

absolutely not new. It was decided at team level several years ago.
it was done to allow all people in the team to have time to have a look whatever timezone they are.

**Comment by lhein** [comment]
Yes, it has been decided we wait 24hrs but not that all have to approve and we did not agree that only after 24hrs and if all approved the flag "ready to merge" can be set.

**Comment by apupier** [comment]
I think you missed the "or" in my sentence:
"all developers of the project approved OR one approval and 24 hours since marked as ready for review"

**Comment by lhein** [comment]
True, I missed that. But there is still the issue with the label.

**Pull request merged**
