### PR TITLE
refactored NewIntegrationFileCommand.ts

### PR DESCRIPTION
**Pull request by lhein**
Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>

### CODE REVIEW

**Comment by lhein** [comment]
that happened automatically when doing `npm install`. I think in an earlier commit this hasn't been done after updating the package.json and that's why it now has a change.

**Comment by apupier** [comment]
> that happened automatically when doing `npm install`. I think in an earlier commit this hasn't been done after updating the package.json and that's why it now has a change.

ok so unrelated to this PR. better to do in a separate PR

**Comment by lhein** [comment]
This is such a minor thing that its not really worth the hassle at all.

**Comment by apupier** [comment]
> This is such a minor thing that its not really worth the hassle at all.

8000+ modifications of lines doesn't sound minor to me

**Comment by lhein** [comment]
And you would review those 8000+ lines if they were in a separate PR, would you? :)

**Comment by apupier** [comment]
> And you would review those 8000+ modifications if they were in a separate PR, would you? :)

I would be able to start discussion about this specific change. Why there are so many changes? Are there ways to avoid big bang like that? more easily be able to compare the result with a local call myself of the "npm install".
These are questions unrelated to the "refactored newIntegrationFileCommand" that I consequently not asked

it will also allow easier browsing of the history/dichotomized potential bug research in case one or the other introduced a problem.

**Comment by lhein** [comment]
depending on #526

**Comment by lhein** [comment]
once #526 has been merged I will rebase this PR

**Comment by apupier** [comment]
I recommend to modify the branch to not be based on the modification of the other PR as they are unrelated.

**Comment by lhein** [comment]
Once the rebase is done the changed package-lock will automatically disappear from this PR as far as I understand.

**Comment by apupier** [comment]
> Once the rebase is done the changed package-lock will automatically disappear from this PR as far as I understand.

you will have to potentially fix conflicts.
Until the other PR is merged, it is then blocking the review and merge of this PR. Having a branch with separated concerns when they don't really depend on each other allows to merge one or the other in whatever order.

**Pull request merged**
