### PR TITLE
attempting to do more optional chaining

### PR DESCRIPTION
**Pull request by bfitzpat**
Signed-off-by: bfitzpat@redhat.com <bfitzpat@redhat.com>

### CODE REVIEW

**Comment by bfitzpat** [comment]
Merging to try and fix the issue that only appears on Jenkins

**Comment by apupier** [comment]
when issue appears only on Jenkins, it is faster and avoids to push changes in master changes by modifying https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/VS%20Code/job/vscode-temporary-testing/ and the jenkins file

**Comment by bfitzpat** [comment]
> when issue appears only on Jenkins, it is faster and avoids to push changes in master changes by modifying https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/VS%20Code/job/vscode-temporary-testing/ and the jenkins file

We should add such details somewhere so we don't lose this information. I will never remember it otherwise

**Comment by apupier** [comment]
> > when issue appears only on Jenkins, it is faster and avoids to push changes in master changes by modifying https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/VS%20Code/job/vscode-temporary-testing/ and the jenkins file
> 
> We should add such details somewhere so we don't lose this information @apupier . I will never remember it otherwise

created https://github.com/jboss-fuse/tooling_material/pull/58

**Pull request merged**
