### PR TITLE
Fix UI Tests missing opencv module error

### PR DESCRIPTION
**Pull request by djelinek**
Signed-off-by: Dominik Jelinek <djelinek@redhat.com>

### CODE REVIEW

**Comment by apupier** [comment]
Can you specify how you manage to fix it please?

**Comment by djelinek** [comment]
Hi @apupier this PR should have been probably named 'Avoid opencv error...' because it only raised tester and added new opencv dependency to package-lock, and problems should not now occurs because your previous commit already removed --ignore-scripts from build steps.. but it is about same problem as in others extensions so I left it as is

**Comment by apupier** [comment]
I merged some other PR, the package-lock.json is in conflict now :-(
Can you rebase please?

**Comment by djelinek** [comment]
no problem, rebased

**Pull request merged**
