### PR TITLE
FUSETOOLS2-239 - update to runtime 1.0.0-RC2

### PR DESCRIPTION
**Pull request by bfitzpat**
Signed-off-by: bfitzpat@redhat.com <bfitzpat@redhat.com>

### CODE REVIEW

**Comment by bfitzpat** [comment]
> the version of the Camel artefact to download must be updated to the version used by this new version of Camel K

It doesn't. We pick up the latest Camel K tag right now in https://github.com/camel-tooling/vscode-camelk/blob/48e33f9876fd7172800aed2c1668d7553d192e91/src/installer.ts#L221

That comes from https://api.github.com/repos/apache/camel-k/releases/latest - which provides the correct tag name 1.0.0-RC2.

**Comment by bfitzpat** [comment]
We still need a way to circumvent that -- as recorded in https://github.com/camel-tooling/vscode-camelk/issues/280 -- so I'll work on that next

**Comment by apupier** [comment]
I was mentioning this version https://github.com/camel-tooling/vscode-camelk/blob/48e33f9876fd7172800aed2c1668d7553d192e91/src/JavaDependenciesManager.ts#L28 which needs to be aligned to this one https://github.com/apache/camel-k-runtime/blob/89b79bd1c347509b407f9454174ace4f4b12f6f6/pom.xml#L38

**Comment by bfitzpat** [comment]
> version for Java completion needs to be updated to 3.0.1

Thanks for the clarification. Just updated that.

**Pull request merged**
