### PR TITLE
FUSETOOLS2-711 - upgrade kubectl to 1.19.0 in Travis infra

### PR DESCRIPTION
**Pull request by apupier**
Signed-off-by: Aurélien Pupier <apupier@redhat.com>

### CODE REVIEW

**Review by bfitzpat — CHANGES_REQUESTED** [review]
Why are we upgrading? Is it just a regular version bump or is there a more specific reason? Can't find anything in the JIRA or the PR

**Comment by apupier** [comment]
> Why are we upgrading? Is it just a regular version bump or is there a more specific reason? Can't find anything in the JIRA or the PR

to fill technical debt.
it also ensures to be working with latest available version.
Dependabot is not able to update automatically as this is not a regular dependency.

**Comment by bfitzpat** [comment]
> to fill technical debt.
> it also ensures to be working with latest available version.
> Dependabot is not able to update automatically as this is not a regular dependency.

This would be good to include in the JIRA so when our QE folks look at it they have some context to base it on. :)

**Comment by apupier** [comment]
> > to fill technical debt.
> > it also ensures to be working with latest available version.
> > Dependabot is not able to update automatically as this is not a regular dependency.
> 
> This would be good to include in the JIRA so when our QE folks look at it they have some context to base it on. :)

done

**Review by bfitzpat — APPROVED** [review]

**Review by lhein — APPROVED** [review]

**Pull request merged**
